---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  namespace: qa
spec:
  generators:
  - git:
      repoURL: https://github.com/codefresh-contrib/gitops-cert-level-2-examples.git
      revision: HEAD
      directories:
      - path: ./environment-promotion/envs/qa/*
  template:
    spec:
      containers:
      - name: webserver-simple
        env:
        - name: ENV
          value: "qa"
        - name: GPU_ENABLED
          value: "0"
      